---

target_os: arch #esxi

# grog.package
package_list:
  - name: bash-completion
  - name: curl
  - name: fio
  - name: git
  - name: hddtemp
  - name: htop
  - name: iftop
  - name: iotop
  - name: lm_sensors
  - name: mc
  - name: ncdu
  - name: net-tools
  - name: nfs-utils
  - name: nmap
  - name: openssh
  - name: open-vm-tools #vmware
  - name: python
  - name: sanoid
  - name: smartmontools
  - name: sudo
  - name: tmux
  - name: tree
  - name: wget
  - name: zfs-linux-lts

# ktz-sanoid
sanoid_config_source: sanoid-morpheus.conf
backup_dataset: backups
backup_dataset_morpheus: "{{ backup_dataset }}/morpheus"
syncoid_healthcheck_url: "curl -fsS --retry 3 https://hc.{{ domain_cloud }}/ping"

syncoid_cron_jobs:
  - { job: '{{ syncoid_binary_path }} -r m:tank {{ backup_dataset_morpheus }}/tank && {{ syncoid_healthcheck_url }}/{{ syncoid_backup_healthcheck_uuid_tank }}', 
      name: 'morpheus_tank_replication', 
      weekday: '*', 
      hour: '*',
      minute: '01' }
  - { job: '{{ syncoid_binary_path }} -r m:intel2tbnvme {{ backup_dataset_morpheus }}/intel2tbnvme && {{ syncoid_healthcheck_url }}/{{ syncoid_backup_healthcheck_uuid_intel2tbnvme }}', 
      name: 'morpheus_intel2tbnvme_replication', 
      weekday: '*', 
      hour: '*',
      minute: '30' }
  - { job: '{{ syncoid_binary_path }} -r m:ssd500-mirror {{ backup_dataset_morpheus }}/ssd500-mirror && {{ syncoid_healthcheck_url }}/{{ syncoid_backup_healthcheck_uuid_ssd500_mirror }}', 
      name: 'morpheus_ssd500-mirror_replication', 
      weekday: '*', 
      hour: '*',
      minute: '45' }
  - { job: '{{ syncoid_binary_path }} -r m:nvme2tb {{ backup_dataset_morpheus }}/nvme2tb && {{ syncoid_healthcheck_url }}/{{ syncoid_backup_healthcheck_uuid_nvme2tb }}', 
      name: 'morpheus_nvme2tb_replication', 
      weekday: '*', 
      hour: '*',
      minute: '55' }