# grog.package
package_list:
    - name: bash-completion
    - name: curl
    - name: htop
    - name: ncdu
    - name: net-tools
    - name: nmap
    - name: sudo
    - name: tmux
    - name: tree
    - name: wget
    - name: wireguard
  
# geerlingguy.security
security_ssh_port: "{{ cloud_ssh_port }}"
security_sudoers_passworded:
- "{{ main_username }}"

# geerlingguy.ntp
ntp_timezone: "America/New_York"

# geerlingguy.docker
# defaults are sane, no need to configure anything
# https://github.com/geerlingguy/ansible-role-docker/blob/master/defaults/main.yml

# geerlingguy.github_users
github_users_authorized_keys_exclusive: true
github_users:
    # You can specify an object with 'name' (required) and 'groups' (optional):
    - name: "{{ main_username }}"
      groups: sudo,docker

# ironicbadger.bash-aliases (formerly ferrarimarco.bash-aliases)
bash_aliases:
    - { alias: "dtail", command: "docker logs -tf --tail='50' " }
    - { alias: "dstop", command: "docker stop `docker ps -aq`" }
    - { alias: "drm", command: "docker rm `docker ps -aq`" }
    - { alias: "dcp", command: "docker-compose -f ~/docker-compose.yml " }
    - { alias: "dprune", command: "docker image prune" }
    - { alias: "dprunesys", command: "docker system prune --all" }
    - { alias: "dtop", command: "docker run --name ctop  -it --rm -v /var/run/docker.sock:/var/run/docker.sock quay.io/vektorlab/ctop" }
    - { alias: "appdata", command: "cd /mnt/tank/appdata" }
    - { alias: "zspace", command: "zfs list -o space" }
    - { alias: "zsnap", command: "zfs list -t snapshot" }

# ironicbadger.docker_compose_generator
appdata_path: "/home/{{ main_username }}/appdata"
containers:
  - service_name: traefik
    active: true
    image: traefik
    container_name: tr
    ports:
        - 80:80
        - 443:443
    volumes:
        - "{{ appdata_path }}/traefik/:/letsencrypt"
        - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
        - "CLOUDFLARE_EMAIL={{ cloudflare_account_email }}"
        - "CLOUDFLARE_API_KEY={{ cloudflare_api_key }}"
    restart: unless-stopped
