---

default_domain: "wd.ktz.me"

network_cidr: 10.42.0.0/20
dhcp_range_start: 10.42.15.100
dhcp_range_end: 10.42.15.250
dhcp_router: 10.42.0.254
dhcp_active: "true"

dns_overrides:
  # try to use sparingly and must be FQDN
  - {ip: 10.42.0.252, custom_dns: "wd.ktz.me"}
  - {ip: 10.42.0.252, custom_dns: "opnsense.wd.ktz.me"}
  - {ip: 10.42.0.252, custom_dns: "dns.wd.ktz.me"}
  - {ip: 10.42.1.99, custom_dns: "hass.ktz.me"}
  - {ip: 10.42.1.10, custom_dns: "nc.ktz.cloud"}

dhcp_reservations:
  # CORE INFRA
  ## c137 - FIREWALL
  - {mac: 7C:2B:E1:13:84:D7, ip: 10.42.0.1, hostname: c137}
  #- {mac: 7C:2B:E1:13:84:D8, ip: 10.42.0.254, hostname: NICnotused}
  #- {mac: 7C:2B:E1:13:84:D9, ip: WAN, hostname: opnsenseWAN} # WAN DHCP - passed through
  - {mac: 7C:2B:E1:13:84:DA, ip: 10.42.0.254, hostname: opnsense, custom_dns: ["opnsense.c137"]} # LAN - passed through
  ### c137 services
  - {mac: 7E:23:21:86:2C:43, ip: 10.42.0.252, hostname: caddy}
  - {mac: FE:31:84:32:25:A3, ip: 10.42.0.253, hostname: pihole}

  ## morpheus - PRIMARY SERVER
  - {mac: D0:50:99:DC:4D:D5, ip: 10.42.1.10, hostname: morpheus, custom_dns: ["m"]} #eno1
  - {mac: D0:50:99:F2:D9:38, ip: 10.42.1.11, hostname: morpheus-ipmi, custom_dns: ["ipmi.m"]}
  ### morpheus services
  - {mac: 3E:79:66:00:87:F7, ip: 10.42.1.99, hostname: ha}
  - {mac: F2:8F:35:40:8A:9C, ip: 10.42.1.98, hostname: redhat-irc}
  - {mac: 92:A9:C6:04:AE:CA, ip: 10.42.1.97, hostname: dev}
  - {mac: BA:F4:A4:1E:EF:C0, ip: 10.42.1.96, hostname: cat-calibre}

  ## anton - BACKUP SERVER
  - {mac: D0:50:99:DB:B2:2D, ip: 10.42.1.20, hostname: anton, custom_dns: ["a"]} #eno1
  - {mac: D0:50:99:F2:8F:57, ip: 10.42.1.21, hostname: anton-ipmi, custom_dns: ["ipmi.a"]} 

  ## m1 - TEST SERVER
  - {mac: E0:D5:5E:2D:FE:61, ip: 10.42.1.30, hostname: m1}

  #########
  ## networking equipment
  - {mac: 04:18:d6:c0:95:62, ip: 10.42.1.40, hostname: unifi-bonus}  
  - {mac: 80:2a:a8:90:4c:9d, ip: 10.42.1.41, hostname: unifi-hallway}  
  - {mac: e0:63:da:33:2a:fd, ip: 10.42.1.42, hostname: unifi-kitchen}  
  - {mac: e0:63:da:67:f3:8c, ip: 10.42.1.43, hostname: unifi-deck}

  #########
  ## misc servers  
  - {mac: e4:5f:01:08:89:ca, ip: 10.42.1.50, hostname: bricktop} #pi4
  - {mac: b8:27:eb:2f:ee:4f, ip: 10.42.1.51, hostname: pi3} #pi3
  - {mac: 38:60:77:0d:ee:6d, ip: 10.42.1.52, hostname: gavinbelson}
  - {mac: 00:18:dd:06:8d:4c, ip: 10.42.1.53, hostname: hdhomerun}
  - {mac: 00:15:64:03:0a:5e, ip: 10.42.1.54, hostname: x32rack}

  #########
  ## media players and TVs
  - {mac: 48:b0:2d:05:2b:61, ip: 10.42.1.60, hostname: shield-bonus}
  - {mac: 00:04:4b:48:e5:f1, ip: 10.42.1.61, hostname: shield-lounge}
  - {mac: cc:a1:2b:6e:18:d7, ip: 10.42.1.62, hostname: roku-kitchen-tv}
  - {mac: 9c:95:61:3b:4c:e5, ip: 10.42.1.63, hostname: roku-lounge-tv}
  - {mac: 74:40:be:ac:99:de, ip: 10.42.1.64, hostname: lgc9-bonus-tv}
  - {mac: ec:0b:ae:98:c8:2b, ip: 10.42.1.65, hostname: broadlink-remote-bonus}

  #########
  ## cameras (Wyze, PoE)
  - {mac: f4:39:09:44:1d:d5, ip: 10.42.2.1, hostname: blueiris}
  
  - {mac: 9c:8e:cd:22:2b:ff, ip: 10.42.2.10, hostname: amcrest-driveway-left}
  - {mac: ec:71:db:ba:75:13, ip: 10.42.2.11, hostname: reolink-driveway-right}
  - {mac: ec:71:db:00:60:b3, ip: 10.42.2.12, hostname: reolink-deck}
  #- {mac: ec:71:db:00:60:b3, ip: 10.42.2.13, hostname: reolink-new1}
  #- {mac: ec:71:db:00:60:b3, ip: 10.42.2.14, hostname: reolink-new2}

  - {mac: 80:91:33:d1:90:f7, ip: 10.42.2.110, hostname: ezviz-doorbell}
  - {mac: d0:3f:27:4e:90:ca, ip: 10.42.2.111, hostname: wyze-bonus}
  - {mac: 2c:aa:8e:fa:36:53, ip: 10.42.2.112, hostname: wyze-nursery}
  - {mac: 7c:78:b2:23:0b:46, ip: 10.42.2.113, hostname: wyze-music-room}
  - {mac: 2c:aa:8e:25:54:2a, ip: 10.42.2.114, hostname: wyze-lounge}
  - {mac: 2c:aa:8e:0b:d4:1e, ip: 10.42.2.115, hostname: wyze-garage}

  #########
  ## local IoT
  - {mac: 2c:f4:32:a9:cf:56, ip: 10.42.5.10, hostname: sonoff_basic_kitchen_hob}
  - {mac: 2c:f4:32:a9:cc:c8, ip: 10.42.5.11, hostname: sonoff_basic_garage_nook_lights}
  - {mac: bc:dd:c2:44:8f:ac, ip: 10.42.5.12, hostname: sonoffsv_garage_door_workshop}
  - {mac: bc:dd:c2:44:8e:93, ip: 10.42.5.13, hostname: sonoffsv_garage_door_car}

  - {mac: 8c:aa:b5:06:06:19, ip: 10.42.5.30, hostname: shelly1pm_masterbed_ceiling_fan}
  - {mac: 8c:aa:b5:05:79:ff, ip: 10.42.5.31, hostname: shelly1pm_garage_driveway_light}
  - {mac: c8:2b:96:10:bf:24, ip: 10.42.5.32, hostname: shelly2_garage_main_lights}
  - {mac: c8:2b:96:10:fa:03, ip: 10.42.5.33, hostname: shelly2_kitchen_lights}

  - {mac: cc:50:e3:03:95:61, ip: 10.42.5.50, hostname: sp20_unknown}
  - {mac: cc:50:e3:03:44:a6, ip: 10.42.5.51, hostname: sp20_loungetv}

  - {mac: 50:02:91:ec:a9:df, ip: 10.42.5.60, hostname: cfsp_bonus_sun}
  - {mac: 50:02:91:ec:e0:9c, ip: 10.42.5.61, hostname: cfsp_driveway_wall_lights}
  - {mac: 50:02:91:ec:a9:de, ip: 10.42.5.62, hostname: cfsp_guest_room_heater}

  - {mac: 24:62:ab:f9:26:9c, ip: 10.42.5.80, hostname: esp32_energy_monitor}
  - {mac: 8c:aa:b5:8c:6c:14, ip: 10.42.5.81, hostname: esp32_xiths_upstairs_bonus}
  - {mac: fc:f5:c4:26:fc:0c, ip: 10.42.5.82, hostname: esp32_xiths_upstairs_bedrooms}

  ### WLED
  - {mac: 84:f3:eb:e3:71:3b, ip: 10.42.5.90, hostname: wled_kitchen_wetbar}

  #########
  ## cloud IoT
  - {mac: 24:6f:28:14:81:7a, ip: 10.42.5.180, hostname: thermoworks-signals}
  - {mac: fc:01:7c:ab:80:6b, ip: 10.42.5.181, hostname: brother-printer}
  - {mac: 50:ec:50:10:ac:fe, ip: 10.42.5.182, hostname: robovac_downstairs}
  - {mac: 50:ec:50:18:ae:7a, ip: 10.42.5.183, hostname: robovac_upstairs}
  - {mac: b4:e6:2d:4e:47:01, ip: 10.42.5.184, hostname: eufy-vac}

  - {mac: 74:40:be:c4:79:cf, ip: 10.42.5.185, hostname: lg-washer}
  - {mac: 2c:2b:f9:97:d8:b7, ip: 10.42.5.186, hostname: lg-dryer}
  - {mac: 74:9e:a5:af:b7:58, ip: 10.42.5.187, hostname: lg-bonusac}


  #   ### Yeelights
  # - {mac: 5c:e5:0c:e1:77:b2, ip: 10.42.5.200, hostname: yeelink_bonus_tinkerspace_1}
  # - {mac: 5c:e5:0c:e1:75:fd, ip: 10.42.5.201, hostname: yeelink_bonus_tinkerspace_2}
  # - {mac: 5c:e5:0c:e1:7a:20, ip: 10.42.5.202, hostname: yeelink_bonus_tinkerspace_3}
  # - {mac: 5c:e5:0c:e1:77:b7, ip: 10.42.5.203, hostname: yeelink_bonus_tv_corner}
  # - {mac: 7c:49:eb:19:93:53, ip: 10.42.5.204, hostname: yeelink_bonus_cat_desk}

  # ### Shelly Bulbs
  # #7c:49:eb:19:93:53
  # #ec:fa:bc:6f:77:bf
  # #ec:fa:bc:6f:77:ee

  #########
  ## primary clients (desktop, servers, laptops, phones, tablets)
  - {mac: f0:2f:4b:00:a3:d5, ip: 10.42.13.10, hostname: slartibartfast}
  - {mac: C4:AC:AA:05:04:16, ip: 10.42.13.11, hostname: alex-iphone}
  - {mac: 4a:15:ad:12:a8:c1, ip: 10.42.13.12, hostname: alex-ipad}
  - {mac: 1e:5d:2f:4d:7f:87, ip: 10.42.13.13, hostname: alex-oneplus7t}

  #- {mac: 00:50:56:9f:22:3c, ip: 10.42.13.40, hostname: cat-ipad}

  #- {mac: 00:50:56:9f:22:3c, ip: 10.42.13.80, hostname: ella-ipad}

  #- {mac: 64:4b:f0:19:05:a3, ip: 10.42.13.100, hostname: caldigit-ts3}
  #- {mac: 64:4b:f0:19:05:a3, ip: 10.42.13.101, hostname: caldigit-ts4}

  #- {mac: 38:ba:f8:59:fd:a3, ip: 10.42.13.110, hostname: t480s-ethernet}
  #- {mac: 38:ba:f8:59:fd:a3, ip: 10.42.13.111, hostname: t480s-wifi}
  #- {mac: 5c:c5:d4:db:65:1e, ip: 10.42.13.112, hostname: x240-ethernet}
  #- {mac: 5c:c5:d4:db:65:1e, ip: 10.42.13.113, hostname: x240-wifi}


