---

ntp_timezone: Europe/London

# ironicbadger.bash-aliases (formerly ferrarimarco.bash-aliases)
bash_aliases_file: /var/services/homes/alexktz/.bashrc
bash_aliases:
  - { alias: "dtail", command: "docker logs -tf --tail='50' " }
  - { alias: "dstop", command: "docker stop `docker ps -aq`" }
  - { alias: "dcp", command: "docker-compose -f ~/docker-compose.yml "}
  - { alias: "dprune", command: "docker image prune" }
  - { alias: "dprunesys", command: "docker system prune --all" }
  - { alias: "dtop", command: "docker run --name ctop  -it --rm -v /var/run/docker.sock:/var/run/docker.sock quay.io/vektorlab/ctop"}
  - { alias: "appdata", command: "cd /volume2/appdata" }

# ironicbadger.docker_compose_generator
global_env_vars:
  - "PUID=1026"
  - "PGID=100"
  - "TZ={{ ntp_timezone }}"
appdata_path: /volume2/appdata
docker_compose_generator_output_path: /var/services/homes/alexktz

containers:
  - service_name: traefik
    active: true
    image: traefik
    container_name: tr
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    command:
      - --log.level=info
      - --accesslog=false
      - --api.insecure=false
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.cloudflare.acme.dnschallenge=true
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - "--certificatesresolvers.cloudflare.acme.email={{ cloudflare_account_email }}"
      - --certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json
      - --serversTransport.insecureSkipVerify=true
    volumes:
      - "{{ appdata_path }}/traefik/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - "CLOUDFLARE_EMAIL={{ cloudflare_account_email }}"
      - "CLOUDFLARE_API_KEY={{ cloudflare_api_key }}"
    restart: unless-stopped
  ###
  - service_name: nginxtest
    active: true
    image: nginx
    labels:
      - traefik.enable=true
      - "traefik.http.routers.nginxtest.rule=Host(`test.el.gg.{{ domain_me }}`)"
      - traefik.http.routers.nginxtest.entrypoints=websecure
      - traefik.http.routers.nginxtest.tls.certresolver=cloudflare
    restart: unless-stopped
  ###
  - service_name: minio
    active: true
    image: minio/minio
    # command: 
    #   - server /data
    labels:
      - traefik.enable=true
      - "traefik.http.routers.minio.rule=Host(`minio.el.gg.{{ domain_me }}`)"
      - traefik.http.routers.minio.entrypoints=websecure
      - traefik.http.routers.minio.tls.certresolver=cloudflare
      - traefik.http.services.minio.loadbalancer.server.port=9000
    command:
      - server 
      - /data 
      - --console-address ':9001'
    volumes:
      - "/volume1/minio:/data"
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ACCESS_KEY=accesskey
      - MINIO_SECRET_KEY=secretkey
    restart: unless-stopped
