---

ntp_timezone: Europe/London

# ironicbadger.bash-aliases (formerly ferrarimarco.bash-aliases)
bash_aliases_file: /var/services/homes/alexktz/.bashrc
bash_aliases:
  - { alias: "dtail", command: "docker logs -tf --tail='50' " }
  - { alias: "dstop", command: "docker stop `docker ps -aq`" }
  - { alias: "dcp", command: "docker-compose -f ~/docker-compose.yml "}
  - { alias: "dprune", command: "docker image prune" }
  - { alias: "dprunesys", command: "docker system prune --all" }
  - { alias: "dtop", command: "docker run --name ctop  -it --rm -v /var/run/docker.sock:/var/run/docker.sock quay.io/vektorlab/ctop"}
  - { alias: "appdata", command: "cd /volume2/appdata" }

# ironicbadger.docker_compose_generator
global_env_vars:
  - "PUID=1026"
  - "PGID=100"
  - "TZ={{ ntp_timezone }}"
appdata_path: /volume2/appdata
docker_compose_generator_output_path: /var/services/homes/alexktz

containers:
  - service_name: traefik
    active: true
    image: traefik
    container_name: tr
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.cloudflare.acme.dnschallenge=true
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - "--certificatesresolvers.cloudflare.acme.email={{ cloudflare_account_email }}"
    volumes:
      - "{{ appdata_path }}/traefik/config:/etc/traefik"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - "CLOUDFLARE_EMAIL={{ cloudflare_account_email }}"
      - "CLOUDFLARE_API_KEY={{ cloudflare_api_key }}"
    restart: unless-stopped
  ###
  - service_name: nginxtest
    active: true
    image: nginx
    labels:
      - traefik.enable=true
      - "traefik.http.routers.nginxtest.rule=Host(`test.el.gg.{{ domain_me }}`)"
      - traefik.http.routers.nginxtest.entrypoints=websecure
      - traefik.http.routers.nginxtest.tls.certresolver=cloudflare
    restart: unless-stopped
  ###
  - service_name: minio
    active: true
    image: minio/minio
    labels:
      - traefik.enable=true
      - "traefik.http.routers.minio.rule=Host(`minio.el.gg.{{ domain_me }}`)"
      - traefik.http.routers.minio.entrypoints=websecure
      - traefik.http.routers.minio.tls.certresolver=cloudflare
    command:
      - server 
      - /data 
      - --address 
      - "0.0.0.0:9000" 
      - --console-address 
      - "0.0.0.0:9001"
    volumes:
      - "/volume1/minio:/data"
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - "MINIO_ROOT_USER={{ elrond_minio_root_user }}"
      - "MINIO_ROOT_PASSWORD={{ elrond_minio_root_password }}"
    restart: unless-stopped
  ###
  - service_name: netdata
    active: true
    image: netdata/netdata
    labels:
      - traefik.enable=true
      - "traefik.http.routers.netdata.rule=Host(`netdata.el.gg.{{ domain_me }}`)"
      - traefik.http.routers.netdata.entrypoints=websecure
      - traefik.http.routers.netdata.tls.certresolver=cloudflare
      - traefik.http.services.netdata.loadbalancer.server.port=19999
    cap_add:
      - SYS_PTRACE
    volumes:
      - "{{ appdata_path }}/netdata:/etc/netdata"
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro