---

hostname: "{{ hosts.lounge.hostname }}"
hostname_lounge: "{{ hostname }}"

## deev-pkg
package_list:
  - gpg
  - python3-pip

## deev-checkmk-agent
checkmk_agent_hash: afb596b83bfbad40

## ironicbadger.docker_compose_generator
appdata_path: /mnt/appdata
wwwdata_path: /mnt/www-data

containers:
  - service_name: ghost
    active: true
    image: ghost:5-alpine
    network_mode: host
    volumes:
      - "{{ appdata_path }}/ghost:/var/lib/ghost/content"
    include_global_env_vars: true
    restart: unless-stopped
    environment:
      - "database__client=sqlite3"
      - "database__connection__filename=\"content/data/ghost.db\""
      - "database__useNullAsDefault=true"
      - "database__debug=false"
      - "url=https://ghost.lounge.{{ default_domain }}"

  - service_name: drone-server
    active: true
    image: drone/drone:latest
    network_mode: host
    volumes:
      - "{{ appdata_path }}/drone-data:/data/"
      - /var/run/docker.sock:/var/run/docker.sock
    include_global_env_vars: true
    restart: unless-stopped
    environment:
      - "DRONE_GITHUB_SKIP_VERIFY=true"
      - "DRONE_SERVER_HOST=drone.{{ domain_deev }}"
      - "DRONE_SERVER_PROTO=https"
      - "DRONE_TLS_AUTOCERT=false"
      - "DRONE_GITHUB=true"
      - "DRONE_USER_CREATE=username:{{ drone_github_user }},machine:false,admin:true,token:{{ drone_github_token }}"
      - "DRONE_USER_FILTER={{ drone_github_user }}"
      - "DRONE_GITHUB_CLIENT_ID={{ drone_github_client_id }}"
      - "DRONE_GITHUB_CLIENT_SECRET={{ drone_github_client_secret }}"
      - "DRONE_RPC_SECRET={{ drone_rpc_secret }}"

  - service_name: drone-docker-agent
    active: true
    image: drone/drone-runner-docker:latest
    network_mode: host
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{ wwwdata_path }}:{{ wwwdata_path }}"
    include_global_env_vars: true
    restart: unless-stopped
    environment:
      - "DRONE_RPC_PROTO=https"
      - "DRONE_RPC_HOST=drone.{{ domain_deev }}"
      - "DRONE_RPC_SECRET={{ drone_rpc_secret }}"

  - service_name: matomo-db
    active: true
    image: mariadb:10.11
    command: "--max-allowed-packet=64MB"
    volumes:
      - /mnt/appdata/matomo/db:/var/lib/mysql:Z
    include_global_env_vars: true
    restart: unless-stopped
    environment:
      - "MYSQL_ROOT_PASSWORD={{ matomo_mariadb_root_password }}"
      - "MARIADB_DISABLE_UPGRADE_BACKUP=1"
      - "MYSQL_PASSWORD={{ matomo_mariadb_password }}"
      - "MYSQL_DATABASE=matomo"
      - "MYSQL_USER=matomo"
      - "MATOMO_DATABASE_ADAPTER=mysql"
      - "MATOMO_DATABASE_TABLES_PREFIX=matomo_"
      - "MATOMO_DATABASE_USERNAME=matomo"
      - "MATOMO_DATABASE_PASSWORD={{ matomo_mariadb_db_password }}"
      - "MATOMO_DATABASE_DBNAME=matomo"
      - "MARIADB_AUTO_UPGRADE=1"
      - "MARIADB_INITDB_SKIP_TZINFO=1"

  - service_name: matomo-app
    active: true
    image: matomo:fpm-alpine
    volumes:
      - /mnt/appdata/matomo/config:/var/www/html/config:z
      - /mnt/appdata/matomo/www-data:/var/www/html:z
    include_global_env_vars: true
    restart: unless-stopped
    environment:
      - "MATOMO_DATABASE_HOST=matomo-db"
      - "PHP_MEMORY_LIMIT=2048M"
      - "MYSQL_PASSWORD={{ matomo_mariadb_password }}"
      - "MYSQL_DATABASE=matomo"
      - "MYSQL_USER=matomo"
      - "MATOMO_DATABASE_ADAPTER=mysql"
      - "MATOMO_DATABASE_TABLES_PREFIX=matomo_"
      - "MATOMO_DATABASE_USERNAME=matomo"
      - "MATOMO_DATABASE_PASSWORD={{ matomo_mariadb_db_password }}"
      - "MATOMO_DATABASE_DBNAME=matomo"
      - "MARIADB_AUTO_UPGRADE=1"
      - "MARIADB_INITDB_SKIP_TZINFO=1"

  - service_name: matomo-nginx
    active: true
    image: nginx:alpine
    volumes:
      - /mnt/appdata/matomo/www-data:/var/www/html:z,ro
      - /mnt/appdata/matomo/matomo.conf:/etc/nginx/conf.d/default.conf:z,ro
    include_global_env_vars: true
    restart: unless-stopped
    ports:
      - 8080:80
