---

target_os: debian
hostname_proxmox: proxmox
main_username: root

# grog.package
package_list:
  - name: bash-completion
  - name: curl
  - name: dnsutils
  - name: fio
  - name: git
  - name: hddtemp
  - name: htop
  - name: ffmpeg
  - name: iftop
  - name: intel-gpu-tools
  - name: iotop
  - name: ipmitool
  - name: lm-sensors
  - name: mc
  - name: mergerfs
  - name: molly-guard
  - name: mutt
  - name: ncdu
  - name: net-tools
  - name: nut
  - name: nut-client
  - name: nut-server
  - name: nfs-kernel-server
  - name: nmap
  - name: nvme-cli
  - name: openssh-server
  - name: python3
  - name: python-setuptools
  - name: screen
  - name: smartmontools
  - name: sudo
  - name: tmux
  - name: tree
  - name: wget
  - name: xfsprogs
  - name: zfsutils-linux
  - name: snapraid

## snapraid
snapraid_config_excludes:
  - "*.unrecoverable"
  - "/tmp/"
  - "/lost+found/"
  - "downloads/"
  - "appdata/"
  - "/mnt/disk7/umbrel/"
  - "*.!sync"
  - ".AppleDouble"
  - "._AppleDouble"
  - ".DS_Store"
  - "._.DS_Store"
  - ".Thumbs.db"
  - ".fseventsd"
  - ".Spotlight-V100"
  - ".TemporaryItems"
  - ".Trashes"
  - ".AppleDB"
  - ".nfo"

## ktz-sanoid
sanoid_build_from_source: true
sanoid_config_source: sanoid-proxmox.conf

# ironicbadger.bash-aliases (formerly ferrarimarco.bash-aliases)
bash_aliases:
  - { alias: "appdata", command: "cd /mnt/nvme0n1/appdata" }
  - { alias: "zspace", command: "zfs list -o space" }
  - { alias: "zsnap", command: "zfs list -o space | sort -k4 --human-numeric-sort" }
  - { alias: "dfclean", command: "df -h -x tmpfs -t fuse.mergerfs -t xfs -t ext4 | sort -k 6" }
  - { alias: "dffull", command: "df -h -x tmpfs -t fuse.mergerfs -t xfs -t ext4 -t zfs" }
  - { alias: "hdtemp", command: "sudo hddtemp -q /dev/sd[a,b,c,d,e,f,g,h,i,j,k,l,m,n]" }
  - { alias: "nvmetemp", command: "nvme smart-log /dev/nvme0n1" }
  - { alias: "itop", command: "sudo intel_gpu_top" }
  - { alias: "bashreload", command: "source ~/.bashrc && echo Bash config reloaded;"}

# deev-proxmox
proxmox_main_storage_path: /mnt/storage
extra_mountpoints:
  - { path: "{{ proxmox_main_storage_path }}" }

# ironicbadger.snapraid
snapraid_runner: false
snapraid_parity_disks:
  - { path: /mnt/parity1, diskbyid: /dev/disk/by-id/ata-ST18000NM000J-2TV103_ZR5DTXYF-part1, fs: xfs, opts: defaults, content: true }

snapraid_data_disks:
  - { path: /mnt/disk1, diskbyid: /dev/disk/by-id/ata-ST18000NM000J-2TV103_ZR5DTKW5-part1, fs: xfs, opts: defaults, content: true }
#  - { path: /mnt/disk2, diskbyid: /dev/disk/by-id/ata-WDC_WD140EDGZ-11B1PA0_Y6GE3JJC-part1, fs: xfs, opts: defaults, content: true }

fstab_mergerfs:
  - { source: "/mnt/disk*:/mnt/tank/fuse", mountpoint: "/mnt/storage", fs: fuse.mergerfs, opts: "defaults,nonempty,allow_other,use_ino,moveonenospc=true,category.create=epmfs,dropcacheonclose=true,minfreespace=250G,fsname=mergerfs" }
  - { source: "/mnt/disk*", mountpoint: "/mnt/jbod", fs: fuse.mergerfs, opts: "defaults,nonempty,allow_other,use_ino,moveonenospc=true,category.create=mspmfs,dropcacheonclose=true,minfreespace=250G,fsname=jbod" }

snapraid_sync_healthcheck_io_uuid: "{{ snapraid_healthcheck_secret }}"

## deev-lxc
lxc_host: "192.168.1.65"
lxc_os_template: "local:vztmpl/ubuntu-22.04-standard_22.04-1_amd64.tar.zst"
lxc_network_gateway: "192.168.1.254"

## sharedom lxc
lxc_sharedom:
  hostname: "sharedom"
  vmid: 1000
  ip: "192.168.1.66/24"
  hwaddr: "e6:30:34:33:36:89"
  mounts: '{"mp0":"/mnt/storage/,mp=/mnt/storage/","mp1":"/mnt/nvme0n1/downloads/,mp=/mnt/downloads/"}'
  diskGB: 1
  unprivileged: true

## lounge lxc
lxc_lounge:
  hostname: "lounge"
  vmid: 1001
  ip: "192.168.1.67/24"
  hwaddr: "5e:c9:1b:b3:b6:a7"
  mounts: '{"mp0":"/mnt/jbod/,mp=/mnt/storage/","mp1":"/mnt/nvme0n1/appdata/,mp=/mnt/appdata/","mp2":"/mnt/nvme0n1/downloads/,mp=/mnt/downloads/"}'
  diskGB: 8
  unprivileged: true

