  ###
  - service_name: tiddlywiki
    active: false
    image: mazzolino/tiddlywiki
    labels:
      - "traefik.http.routers.tiddlywiki.rule=Host(`wiki.m.wd.{{ domain }}`)"
      - traefik.http.services.tiddlywiki.loadbalancer.server.port=8080
    environment:
      - USERNAME=
      - PASSWORD=
    volumes:
      - "{{ appdata_path }}/tiddlywiki:/var/lib/tiddlywiki"
    restart: unless-stopped
  ###
  - service_name: nextcloud
    active: false
    image: nextcloud:stable
    depends_on:
      - mysql
    labels:
      - "traefik.http.routers.nc.rule=Host(`nc.{{ domain_cloud }}`)"
    volumes:
      - "{{ appdata_path }}/nextcloud:/var/www/html"
    restart: unless-stopped
  ###
  - service_name: mysql
    active: false
    image: mariadb
    ports:
      - 3306:3306
    environment:
      - "MYSQL_ROOT_PASSWORD={{ container_mysql_root_password }}"
      - "MYSQL_PASSWORD={{ container_mysql_password }}"
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    volumes:
      - "{{ appdata_path }}/mysql:/var/lib/mysql"
    restart: unless-stopped
  ###
  - service_name: sync
    active: false
    image: linuxserver/resilio-sync
    hostname: "{{ hostname_morpheus }}"
    volumes:
      - "{{ appdata_path }}/sync:/config"
      #- "{{ morpheus_main_storage_path }}:/sync" # make the scope smaller
    labels:
      - "traefik.http.routers.btsync.rule=Host(`sync.m.{{ local_domain }}`)"
    ports:
      - "55555:55555"
    include_global_env_vars: true
    restart: unless-stopped
  ###
  - service_name: lychee
    active: false
    image: lycheeorg/lychee
    labels:
      - "traefik.http.routers.lychee.rule=Host(`gallery.m.{{ local_domain }}`)"
    depends_on:
      - mysql
    volumes:
      - "{{ appdata_path }}/lychee/config:/config"
      - "{{ appdata_path }}/lychee/uploads:/uploads"
      - "{{ appdata_path }}/lychee/sym:/sym"
    environment:
      - PHP_TZ=America/New_York
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=lychee
      - DB_DATABASE=lychee
      - "DB_PASSWORD={{ container_mysql_password }}"
    include_global_env_vars: true
    restart: unless-stopped
  ###
  - service_name: paperless
    active: false
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    labels:
      - "traefik.http.routers.paperless.rule=Host(`paperless.m.{{ local_domain }}`)"
    volumes:
      - "{{ appdata_path }}/paperless/config:/config"
      - "{{ appdata_path }}/paperless/data:/data"
    environment:
      - PAPERLESS_CONSUMER_RECURSIVE=true
      - PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS=true
      - PAPERLESS_URL=https://paperless.m.{{ local_domain }}
      - PAPERLESS_REDIS=redis://redis
    include_global_env_vars: true
    restart: unless-stopped
  ###
  - service_name: code
    active: false
    image: lscr.io/linuxserver/code-server:latest
    environment:
      - "PASSWORD=1234"
      - "PROXY_DOMAIN=code.m.{{ local_domain }}" #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    labels:
      - "traefik.http.routers.code.rule=Host(`code.m.{{ local_domain }}`)"
    volumes:
      - "{{ appdata_path }}/code/config:/config"
    include_global_env_vars: true
    restart: unless-stopped
  ###
  - service_name: prometheus
    active: false
    image: prom/prometheus
    labels:
      - "traefik.http.routers.prom.rule=Host(`prom.m.{{ local_domain }}`)"
    ports:
      - 9091:9090
    privileged: true
    volumes:
      - "{{ appdata_path }}/prometheus:/etc/prometheus"
    restart: unless-stopped
  ###
  - service_name: grafana
    active: false
    image: grafana/grafana
    labels:
      - "traefik.http.routers.grafana.rule=Host(`grafana.m.{{ local_domain }}`)"
      - traefik.http.services.grafana.loadbalancer.server.port=3000
    environment:
      - "GF_SERVER_ROOT_URL=https://grafana.m.wd.{{ local_domain }}"
      - "GF_SERVER_SERVE_FROM_SUB_PATH=true"
      - "GF_SERVER_DOMAIN=grafana.m.{{ local_domain }}"
    volumes:
      - "{{ appdata_path }}/grafana/data:/var/lib/grafana"
    restart: unless-stopped
  ###
  - service_name: abs
    active: true
    image: advplyr/audiobookshelf
    labels:
      - "traefik.http.routers.audiobookshelf.rule=Host(`abs.m.{{ local_domain }}`)"
    volumes:
      - "{{ morpheus_main_storage_path }}/audiobooks/library:/audiobooks:ro"
      - "{{ morpheus_main_storage_path }}/audiobooks/library2:/audiobooks2:ro"
      - "{{ morpheus_main_storage_path }}/audiobooks/podcasts:/podcasts"
      - "{{ appdata_path }}/audiobookshelf/metadata:/metadata"
      - "{{ appdata_path }}/audiobookshelf/config:/config"
    restart: unless-stopped
  ###
  - service_name: overseerr
    active: true
    image: sctx/overseerr:latest
    labels:
      - "traefik.http.routers.overseerr.rule=Host(`overseerr.m.{{ local_domain }}`)"
    volumes:
      - "{{ appdata_path }}/overseerr:/app/config"
    restart: unless-stopped