- src: ironicbadger.bash_aliases
- src: ironicbadger.figurine
- src: ironicbadger.hddtemp
- src: ironicbadger.snapraid
- src: ironicbadger.proxmox_nag_removal
- src: cloudalchemy.prometheus
- src: ironicbadger.docker_compose_generator
- src: geerlingguy.docker
- src: grog.package