- src: ironicbadger.figurine
- src: ironicbadger.hddtemp
- src: ironicbadger.snapraid
- src: ironicbadger.proxmox_nag_removal
- src: ironicbadger.docker_compose_generator
- src: geerlingguy.docker
- src: artis3n.tailscale
- src: bertvv.dnsmasq