---
  - hosts: c137
    vars_files:
      - 'vars/vault.yaml'
    roles:
      - role: grog.package
      - role: ironicbadger.proxmox_nag_removal
      - role: ironicbadger.bash_aliases
      - role: ironicbadger.figurine

  - hosts: morpheus
    vars_files:
      - 'vars/vault.yaml'
    roles:
      - role: geerlingguy.docker
      - role: grog.package
      #- role: rossmcdonald.telegraf
      - role: ironicbadger.hddtemp
      - role: ironicbadger.proxmox_nag_removal
      - role: ironicbadger.bash_aliases
      - role: ironicbadger.figurine
      - role: ironicbadger.apprise_boot_notification
      - role: ktz-sanoid
        tags: replication
      - role: ktz-morpheus
      - role: geerlingguy.nfs
      #- role: ktz-apcupsd
      - role: ktz-authelia
        tags: compose
      - role: ironicbadger.docker_compose_generator
        tags: compose
      - role: ktz-traefik
        tags: compose
      - role: ironicbadger.snapraid
      - role: ktz-plexmetamanager
        tags: compose
      - role: ktz-autorestic
        tags: replication

  - hosts: pennywise
    vars_files:
      - 'vars/vault.yaml'
    roles:
      - role: geerlingguy.docker
      - role: grog.package
      - role: ironicbadger.hddtemp
      #- role: ironicbadger.proxmox_nag_removal
      - role: ironicbadger.bash_aliases
      - role: ironicbadger.figurine
      - role: ironicbadger.apprise_boot_notification
      - role: ktz-sanoid
      - role: ktz-traefik
      - role: ironicbadger.docker_compose_generator
        tags: compose

  - hosts: anton
    vars_files:
      - 'vars/vault.yaml'
    roles:
      - role: geerlingguy.docker
      - role: artis3n.tailscale
      - role: grog.package
      - role: ironicbadger.proxmox_nag_removal
      - role: ironicbadger.hddtemp
      - role: ironicbadger.bash_aliases
      - role: ironicbadger.figurine
      - role: ironicbadger.apprise_boot_notification
      - role: ktz-sanoid

  - hosts: m1
    vars_files:
      - 'vars/vault.yaml'
    roles:
      - role: geerlingguy.docker
      - role: grog.package
      - role: ironicbadger.proxmox_nag_removal
      - role: ironicbadger.figurine

  - hosts: cloud
    vars_files:
      - 'vars/vault.yaml'
    roles:
      - role: geerlingguy.docker
      - role: artis3n.tailscale
      - role: grog.package
      - role: ironicbadger.bash_aliases
      - role: ironicbadger.figurine
      #- role: ktz-sanoid
      - role: ktz-traefik
      - role: ironicbadger.docker_compose_generator
        tags: compose

  - hosts: dhcp-dns
    vars_files:
      - 'vars/vault.yaml'
    roles:
      - role: ironicbadger.bash_aliases
      - role: ktz-dhcp-dns

  - hosts: elrond
    vars_files:
      - 'vars/vault.yaml'
    roles:
      #- role: ironicbadger.bash_aliases
      - role: ironicbadger.docker_compose_generator
        tags: compose

  - hosts: galgatebst
    vars_files:
      - 'vars/vault.yaml'
    roles:
      - role: grog.package
      - role: geerlingguy.docker
      - role: geerlingguy.ntp
      - role: ironicbadger.bash_aliases
      - role: ironicbadger.figurine
    tasks:
      - hostname:
          name: "galgatebst"

  - hosts: vpnwd
    vars_files:
      - 'vars/vault.yaml'
    roles:
      - role: grog.package
      - role: ironicbadger.apprise_boot_notification
      - role: ironicbadger.figurine
    tasks:
      - hostname:
          name: "vpnwd"

  - hosts: opnsensewd
    vars_files:
      - 'vars/vault.yaml'
    roles:
      - role: ironicbadger.figurine
      - role: geerlingguy.ntp
      - role: ktz-opnsense-caddy

  - hosts: caddy
    vars_files:
      - 'vars/vault.yaml'
    roles:
      - role: ironicbadger.figurine
      - role: geerlingguy.ntp
      - role: ktz-caddy

  - hosts: nginx
    vars_files:
      - 'vars/vault.yaml'
    roles:
      - role: ironicbadger.figurine
      - role: geerlingguy.ntp
      - role: geerlingguy.docker

  - hosts: tailscale
    vars_files:
      - 'vars/vault.yaml'
    roles:
      - role: ironicbadger.figurine
      - role: geerlingguy.ntp
      - role: artis3n.tailscale

  - hosts: c137-services
    vars_files:
      - 'vars/vault.yaml'
    pre_tasks:
      - name: Update APT Cache
        become: true
        apt:
          update_cache: yes
    tasks:
      - name: Update packages
        ansible.builtin.apt:
          update_cache: "True"
          force_apt_get: "True"
          cache_valid_time: 3600
          upgrade: "True"

      - name: Check if a reboot is needed for Debian and Ubuntu boxes
        register: reboot_required_file
        ansible.builtin.stat:
          path: /var/run/reboot-required
          get_md5: no

      - name: Reboot the server
        throttle: 1
        ansible.builtin.reboot:
          msg: Reboot initiated by Ansible due to updates which require one
          connect_timeout: 5
          reboot_timeout: 300
          pre_reboot_delay: 0
          post_reboot_delay: 30
          test_command: uptime
        when: reboot_required_file.stat.exists

    roles:
      - role: ironicbadger.figurine
      - role: geerlingguy.ntp