---

  - hosts: proxmox
    vars_files:
      - 'vars/vault.yaml'
    roles:
      - role: deev-pkg
      - role: ironicbadger.figurine
      - role: ironicbadger.hddtemp
      - role: ironicbadger.proxmox_nag_removal
      - role: deev-proxmox
      - role: ktz-sanoid
      - role: ironicbadger.snapraid
      - role: deev-checkmk-agent

  - hosts: caddy
    vars_files:
      - 'vars/vault.yaml'
    roles:
      - role: deev-pkg
      - role: ktz-caddy
      - role: deev-checkmk-agent

  - hosts: samba
    vars_files:
      - 'vars/vault.yaml'
    roles:
      - role: deev-pkg
      - role: vladgh.samba.server
      - role: deev-checkmk-agent

  - hosts: tailscale
    vars_files:
      - 'vars/vault.yaml'
    roles:
      - role: deev-pkg
      - role: deev-tailscale
      - role: deev-checkmk-agent

  - hosts: plex
    vars_files:
      - 'vars/vault.yaml'
    roles:
      - role: deev-pkg
      - role: geerlingguy.docker
      - role: deev-docker-compose
        tags: compose
      - role: deev-checkmk-agent
    tasks:
      - name: install python docker for checkmk
        tags: checkmkagent
        ansible.builtin.pip:
          name:
            - docker
            - python-docker

  - hosts: dnsmasq
    vars_files:
      - 'vars/vault.yaml'
    roles:
      - role: deev-pkg
      - role: deev-dhcp
      - role: deev-checkmk-agent

  - hosts: checkmk
    vars_files:
      - 'vars/vault.yaml'
    roles:
      - role: deev-pkg
      - role: deev-checkmk-server
      - role: deev-checkmk-agent

  - hosts: nextcloud
    vars_files:
      - 'vars/vault.yaml'
    roles:
      - role: deev-pkg
      - role: geerlingguy.docker
      - role: deev-docker-compose
        tags: compose
      - role: deev-checkmk-agent
    tasks:
      - name: install python docker for checkmk
        tags: checkmkagent
        ansible.builtin.pip:
          name:
            - docker
            - python-docker

  - hosts: lounge
    vars_files:
      - 'vars/vault.yaml'
    roles:
      - role: deev-pkg
      - role: geerlingguy.docker
      - role: deev-docker-compose
        tags: compose
      - role: deev-checkmk-agent
    tasks:
      - name: install python docker for checkmk
        tags: checkmkagent
        ansible.builtin.pip:
          name:
            - docker
            - python-docker
