---

- name: install caddy service file
  template:
    src: templates/caddy.service.j2
    dest: "/etc/systemd/system/caddy.service"

- name: ensure Caddyfile target dir exists
  file:
    path: "{{ caddy_linux_caddyfile_path }}"
    state: directory

- name: template and install Caddyfile
  template:
    src: templates/Caddyfile.j2
    dest: "{{ caddy_linux_caddyfile_path }}/Caddyfile"

- name: template and install exposed config
  template:
    src: templates/exposed.caddy.j2
    dest: "{{ caddy_linux_caddyfile_path }}/exposed.caddy"

- name: template and install internal config
  template:
    src: templates/internal.caddy.j2
    dest: "{{ caddy_linux_caddyfile_path }}/internal.caddy"

- name: enable caddy service
  ansible.builtin.systemd:
    name: caddy
    enabled: true
    state: reloaded
    daemon_reload: true
