---

- name: install xcaddy
  ansible.builtin.apt:
    deb: "{{ xcaddy_binary_url }}"

- name: build caddy
  ansible.builtin.shell:
    cmd: xcaddy build latest --with github.com/caddy-dns/cloudflare --with github.com/WeidiDeng/caddy-cloudflare-ip --with github.com/hslatman/caddy-crowdsec-bouncer --output /usr/local/bin/caddy

- name: create caddy config folder
  ansible.builtin.file:
    path: "{{ caddy_data_path }}/caddy"
    state: directory
    mode: '0755'

- name: create caddy logs folder
  ansible.builtin.file:
    path: "{{ caddy_log_path }}"
    state: directory
    mode: '0755'
