---

- name: ensure hostname is set correctly
  hostname:
    name: "{{ hostname_caddy }}"

- name: install caddy
  include_tasks:
    file: install.yaml

- name: configure caddy rules
  include_tasks:
    file: configure.yaml
  tags:
  - config