---

- name: ensure hostname is set correctly
  hostname:
    name: "{{ hostname_caddy }}"

- name: install crowdsec
  import_tasks:
    file: crowdsec.yaml
  when: crowdsec

- name: install caddy
  import_tasks:
    file: install.yaml

- name: configure caddy rules
  import_tasks:
    file: configure.yaml
  tags:
    - config
