---
- name: ensure target dir exists
  file:
    dest: "{{ appdata_path }}/traefik/"
    state: directory
    owner: "root"
    group: "root"

- name: template traefik config
  template:
    src: templates/traefik.yaml.j2
    dest: "{{ appdata_path }}/traefik/traefik.yaml"
    owner: "root"
    group: "root"
  tags: traefik

- name: copy traefik rules
  template:
    src: templates/rules.yaml.j2
    dest: "{{ appdata_path }}/traefik/rules.yaml"
    owner: "root"
    group: "root"
  when: traefik_file_provider
  tags: traefik