---
- name: ensure target dir exists
  file:
    dest: "{{ appdata_path }}/traefik/"
    state: directory
    owner: "{{ main_uid }}"
    group: "{{ main_gid }}"

- name: copy traefik config
  copy:
    src: traefik/traefik.yaml
    dest: "{{ appdata_path }}/traefik/traefik.yaml"
    owner: "{{ main_uid }}"
    group: "{{ main_gid }}"
  tags: traefik

- name: copy traefik rules
  copy:
    src: traefik/rules.yaml
    dest: "{{ appdata_path }}/traefik/rules.yaml"
    owner: "{{ main_uid }}"
    group: "{{ main_gid }}"
  when: enable_traefik_external_rules
  tags: traefik