http:
  routers:
    router-homeassistant:
      entryPoints:
        - websecure
      rule: Host(`ha.ktz.me`)
      service: service-homeassistant
      tls:
        certResolver: cloudflare
    router-blueiris:
      entryPoints:
        - websecure
      rule: Host(`bi.ktz.me`)
      service: service-blueiris
      tls:
        certResolver: cloudflare
  services:
    service-homeassistant:
      loadBalancer:
        servers:
        - url: "http://192.168.1.99:8123"
    service-blueiris:
      loadBalancer:
        servers:
        - url: "http://192.168.1.200:81"