---

- name: install required packages
  ansible.builtin.apt:
    pkg: "{{ package_list }}"
    state: present

- name: upgrade packages
  ansible.builtin.apt:
    state: present
    upgrade: yes
    update_cache: yes
  tags: update-packages