---

- name: install required packages
  ansible.builtin.apt:
    pkg: "{{ package_list }}"
    state: present

- name: upgrade packages
  ansible.builtin.apt:
    state: present
    upgrade: true
    update_cache: true
  tags: update-packages
