---

- name: check if figurine is installed already
  stat:
    path: /usr/local/bin/figurine
  register: file_result

- name: download and unpack figurine
  unarchive:
    src: https://github.com/arsham/figurine/releases/download/v1.1.3/figurine_linux_v1.1.3.tar.gz
    dest: /tmp
    remote_src: True
  when: not file_result.stat.exists

- name: move extracted file to bin directory
  command: mv /tmp/deploy/figurine /usr/local/bin/
  when: not file_result.stat.exists

- name: configure login
  template:
    src: figurine.sh.j2
    dest: /etc/profile.d/figurine.sh
  when: not file_result.stat.exists